fsbm_transform:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /app/data/duckdb/fsbm.duckdb
      # Le message d'erreur indique que la base doit s'appeler 'fsbm'
      database: fsbm 
      schema: clean_data