import json
import logging
import sys

# Configure structured logging to flush immediately to stdout
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)]
)
logger = logging.getLogger("fsbm-backend")

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from prometheus_fastapi_instrumentator import Instrumentator
from prometheus_client import Counter

from opentelemetry.instrumentation.logging import LoggingInstrumentor
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor
from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import OTLPSpanExporter
from opentelemetry import trace

logger.info("Importing chat engine modules...")
from src.chat_engine import get_chat_engine, ground_emails_in_answer
from src.generate_title import generate_conversation_title


# Initialize OpenTelemetry Export Pipeline
provider = TracerProvider()
provider.add_span_processor(BatchSpanProcessor(OTLPSpanExporter()))
trace.set_tracer_provider(provider)

tracer = trace.get_tracer(__name__)

# Automatically inject Trace IDs into all Python stdout logs
LoggingInstrumentor().instrument(set_logging_format=True)

# Define the custom MLOps metric
LLM_TOKENS = Counter(
    "llm_tokens_generated_total",
    "Total tokens generated by the LLM",
    ["model"]
)

logger.info("Initializing FastAPI application...")
app = FastAPI(
    title="API Chatbot FSBM",
    description="API RAG pour interroger les données de la Faculté des Sciences Ben M'Sik",
    version="1.0.0"
)

# Instrument FastAPI to trace all HTTP requests
FastAPIInstrumentor.instrument_app(app)

# Initialisation de l'instrumentation Prometheus
instrumentator = Instrumentator(
    should_group_status_codes=False,
    should_ignore_untemplated=True,
    should_respect_env_var=True,
    should_instrument_requests_inprogress=True,
    excluded_handlers=[".*admin.*", "/metrics"],
    env_var_name="ENABLE_METRICS",
)
instrumentator.instrument(app).expose(app, include_in_schema=False)

# Configuration du CORS pour autoriser Next.js à communiquer avec l'API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # En production, on mettra ["http://localhost:3000", "ton-domaine.com"]
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# print("Chargement du modèle et de la base vectorielle...")
logger.info("Building chat engine and connecting to vector store...")
chat_engine = get_chat_engine()
logger.info("Chat engine successfully loaded and ready.")
# print("Moteur IA prêt !")


class ChatRequest(BaseModel):
    question: str

class TitleRequest(BaseModel):
    prompt: str
    language: str | None = None
    exception_titles: list[str] | None = None

def sse_event(data: dict) -> str:
    """Formats one Server-Sent-Event block. The frontend splits on '\\n\\n'
    and strips a leading 'data: ' prefix, then JSON.parses what's left -
    so every event MUST end with a blank line, and the payload MUST be a
    JSON object with 'type' and 'text' keys (event.type / event.text on
    the frontend)."""
    return f"data: {json.dumps(data, ensure_ascii=False)}\n\n"


def generate_chat_stream(question: str):
    full_answer = ""
    context_docs = None
    try:
        with tracer.start_as_current_span("rag_and_llm_generation") as span:
            span.set_attribute("chat.question", question)
            logger.info(f"Starting RAG generation for question: {question}")
            for chunk in chat_engine.stream({"input": question}):
                if "context" in chunk:
                    context_docs = chunk["context"]

                piece = chunk.get("answer")
                if piece:
                    full_answer += piece
                    LLM_TOKENS.labels(model="qwen2.5:3b").inc(1)
                    yield sse_event({"type": "delta", "text": piece})

        with tracer.start_as_current_span("ground_emails_postprocess"):
            grounded_answer = ground_emails_in_answer(full_answer, context_docs, question)
            yield sse_event({"type": "done", "text": grounded_answer})

    except Exception as e:
        yield sse_event({"type": "error", "text": str(e)})


@app.post("/api/chat", tags=["Chat"])
async def chat_endpoint(request: ChatRequest):
    if not request.question or not request.question.strip():
        raise HTTPException(status_code=400, detail="La question ne peut pas être vide.")

    return StreamingResponse(
        generate_chat_stream(request.question),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache, no-transform",
            "Connection": "keep-alive",
            # Disables buffering on nginx-style proxies sitting in front of
            # uvicorn, so chunks reach the browser as they're produced.
            "X-Accel-Buffering": "no",
        },
    )

@app.post("/generate-title")
async def api_generate_title(request: TitleRequest):
    try:
        title_info = await generate_conversation_title(
            prompt=request.prompt,
            language=request.language,
            exception_titles=request.exception_titles
        )

        return {
            "title": title_info["title"],
            "language": title_info["target_language"],
            "detected_language": title_info["detected_language"]
        }

    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Title generation failed: {str(e)}"
        )


def _sse_event(event_type: str, text: str) -> str:
    """Formats one Server-Sent Event. Payload is JSON-encoded so that
    newlines or special characters inside the answer text can't break
    the SSE framing (which relies on blank-line-terminated messages)."""
    payload = json.dumps({"type": event_type, "text": text}, ensure_ascii=False)
    return f"data: {payload}\n\n"


def _stream_answer(question: str):
    accumulated_answer = ""
    context_docs = None

    try:
        with tracer.start_as_current_span("rag_and_llm_generation") as span:
            span.set_attribute("chat.question", question)
            logger.info(f"Starting RAG generation for question: {question}")
            for chunk in chat_engine.stream({"input": question}):
                if "context" in chunk and context_docs is None:
                    context_docs = chunk["context"]
                if "answer" in chunk and chunk["answer"]:
                    accumulated_answer += chunk["answer"]
                    LLM_TOKENS.labels(model="qwen2.5:3b").inc(1)  # <-- Add this line
                    yield _sse_event("delta", chunk["answer"])

        with tracer.start_as_current_span("ground_emails_postprocess"):
            final_answer = ground_emails_in_answer(accumulated_answer, context_docs, question)
            yield _sse_event("done", final_answer)

    except Exception as e:
        yield _sse_event("error", str(e))


@app.post("/api/chat/stream", tags=["Chat"])
async def chat_stream_endpoint(request: ChatRequest):
    """Streaming endpoint: emits the answer live, token by token, via
    Server-Sent Events. Use this for the website's chat UI."""
    return StreamingResponse(
        _stream_answer(request.question),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",  # disables nginx response buffering, if you're behind one
        },
    )


@app.get("/api/health", tags=["Système"])
async def health_check():
    return {"status": "L'API FSBM est opérationnelle"}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)